title: The Internet was made for kittens
description: A personal website powered by Jekyll
baseurl: ""
url: "https://scer80.github.io"
github_username: scer80

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

# Theme specific settings
style: dark  # This ensures dark background with light text
listen_for_clients_preferred_style: false  # This prevents the theme from using system preferences

# Header settings (optional)
header_pages:
  - index.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor