title: The Internet was made for kittens
description: A personal website powered by Jekyll
baseurl: ""
url: "https://scer80.github.io"
github_username: scer80

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Theme specific settings
style: dark # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor